### ISSUE TITLE
Hello samuel ewudzi incoom and bunnyCDN, please add ability to rename files and folders on the bunnycdn admin panel like filezilla

### ISSUE THREAD

**Issue by mikzoomjson** [Samuelincoom/bunnycarrot#2]
Hello samuel ewudzi incoom and bunnyCDN, please add ability to rename files and folders on the bunnycdn admin panel like filezilla. Good on this plugin and bunny's new official plugin. works flawlessly for me

**Comment by Samuelincoom** [comment]
Thanks, but this place is meant only for issues you find on my plugin.
